import { clientsClaim } from 'workbox-core'
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { BackgroundSyncPlugin } from 'workbox-background-sync'

clientsClaim()
self.skipWaiting()

// Precache all assets generated by Vite + any additional ones
precacheAndRoute(self.__WB_MANIFEST || [])
cleanupOutdatedCaches()

// Offline fallback page for navigations
const OFFLINE_URL = '/offline.html'

registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'html-cache',
    networkTimeoutSeconds: 5,
    plugins: [
      {
        handlerDidError: async () => {
          const cache = await caches.open('html-cache')
          const cached = await cache.match(OFFLINE_URL)
          return cached || Response.error()
        }
      }
    ]
  })
)

// Static assets: JS, CSS, fonts, images – CacheFirst
registerRoute(
  ({ request }) =>
    ['style', 'script', 'worker'].includes(request.destination) ||
    request.destination === 'font' ||
    request.destination === 'image',
  new CacheFirst({
    cacheName: 'static-assets-cache-v1'
  })
)

// API requests – NetworkFirst with background sync for writes
const apiBackgroundSyncPlugin = new BackgroundSyncPlugin('api-queue', {
  maxRetentionTime: 24 * 60 // Retry for up to 24 hours
})

registerRoute(
  ({ url, request }) =>
    url.pathname.startsWith('/api/') &&
    ['POST', 'PUT', 'PATCH', 'DELETE'].includes(request.method),
  new NetworkFirst({
    cacheName: 'api-write-cache',
    plugins: [apiBackgroundSyncPlugin]
  }),
  'POST'
)

registerRoute(
  ({ url, request }) =>
    url.pathname.startsWith('/api/') && request.method === 'GET',
  new NetworkFirst({
    cacheName: 'api-cache-v1'
  })
)

// Push notifications
self.addEventListener('push', (event) => {
  if (!event.data) return
  const data = event.data.json()

  const title = data.title || 'Basket Notification'
  const options = {
    body: data.body || '',
    icon: '/icons/icon-192x192.png',
    badge: '/icons/icon-192x192.png',
    data: data.data || {},
    actions: data.actions || []
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const url = event.notification.data?.url || '/'
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client) {
          return client.focus()
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(url)
      }
      return undefined
    })
  )
})

